version: '3'
services:
  web:
    build:
      context: . # Hier den Kontext auf das Hauptverzeichnis setzen, nicht auf ./app
      dockerfile: Dockerfile # Der Dockerfile sollte im Hauptverzeichnis sein
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=todos
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - mynetwork
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/mysql:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge
