version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Automatisches Ausführen des SQL-Skripts beim Start
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
