version: '3'
services:
  web:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=todos
    networks:
      - mynetwork

      
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - mynetwork
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge
