name: Build and Push Docker Images

on:
  push:
    branches:
      - master  # Oder main, abhängig von deinem Branch-Namen
    paths:
      - '**/*.js'
      - '**/*.yml'
      - '**/*.json'
      - '**/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build -t jakobfh/ass3_app_1:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push jakobfh/ass3_app_1:latest
