name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - "app/**"   # nur Änderungen im app-Verzeichnis lösen den Workflow aus

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout des Codes aus dem Repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Docker Setup für die GitHub Actions Runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Logge dich in die GitHub Container Registry ein
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Baue das Docker-Image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/ass3_app_1:latest .
      
      # Push das Docker-Image in die GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/ass3_app_1:latest
